import { describe, test, expect, beforeAll, afterAll } from "bun:test";
import { spawn } from "child_process";
import path from "path";
import fs from "fs";

// Random ports for both CDPX server and browser instance
const SERVER_PORT = 30000 + Math.floor(Math.random() * 30000);
// Token will be auto-generated by server, read after startup
const TOKEN_FILE = path.resolve(import.meta.dirname!, "..", ".token");
let TOKEN = "";
try { TOKEN = fs.readFileSync(TOKEN_FILE, "utf-8").trim(); } catch {}
const authQ = () => TOKEN ? `token=${TOKEN}` : "";
const BASE = `http://127.0.0.1:${SERVER_PORT}/api/browser`;
let PORT = 40000 + Math.floor(Math.random() * 20000);
let TAB_ID = "";
let CREATED_TABS: string[] = [];
let serverProc: ReturnType<typeof spawn> | null = null;

// Start our own CDPX server
const serverTs = path.resolve(import.meta.dirname!, "..", "web", "server.ts");
serverProc = spawn("bun", [serverTs], {
  env: { ...process.env, PORT: String(SERVER_PORT) },
  stdio: "ignore",
  detached: true,
});
serverProc.unref();

// Wait for server to be ready
for (let i = 0; i < 20; i++) {
  const ok = await fetch(`http://127.0.0.1:${SERVER_PORT}/api/browser/status?${authQ()}`).then((r) => r.ok).catch(() => false);
  if (ok) break;
  // Re-read token (server creates it on first run)
  try { TOKEN = fs.readFileSync(TOKEN_FILE, "utf-8").trim(); } catch {}
  await Bun.sleep(500);
}
const alive = await fetch(`http://127.0.0.1:${SERVER_PORT}/api/browser/status?${authQ()}`).then((r) => r.ok).catch(() => false);
if (!alive) {
  console.error(`\n  \x1b[31mFailed to start CDPX on :${SERVER_PORT}\x1b[0m\n`);
  serverProc?.kill();
  process.exit(1);
}

async function post(p: string, body: Record<string, unknown> = {}) {
  const sep = p.includes("?") ? "&" : "?";
  return (await fetch(`${BASE}${p}${TOKEN ? sep + authQ() : ""}`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
  })).json();
}

async function get(p: string) {
  const sep = p.includes("?") ? "&" : "?";
  return (await fetch(`${BASE}${p}${TOKEN ? sep + authQ() : ""}`)).json();
}

async function openTestTab(url = "https://www.google.com") {
  const data: any = await post("/open", { port: PORT, url });
  if (data.tab?.id) CREATED_TABS.push(data.tab.id);
  return data.tab?.id || "";
}

// ─── Setup ──────────────────────────────────────────

beforeAll(async () => {
  // Start a fresh instance on random port
  await post("/start", { ports: [PORT] });
  await Bun.sleep(3000);

  // Create a dedicated test tab
  TAB_ID = await openTestTab();
  if (!TAB_ID) throw new Error("Failed to create test tab");
  await Bun.sleep(2000);
}, 15000);

afterAll(async () => {
  for (const id of CREATED_TABS) {
    await post("/close-tab", { port: PORT, tabId: id }).catch(() => {});
  }
  await post("/stop", { port: PORT }).catch(() => {});
  // Kill the test server
  if (serverProc?.pid) {
    try { process.kill(-serverProc.pid); } catch {}
  }
});

// ─── Server ─────────────────────────────────────────

describe("Server", () => {
  test("GET /status", async () => {
    const data: any = await get("/status");
    expect(data.instances).toBeDefined();
  });

  test("POST /connect", async () => {
    const data: any = await post("/connect", { port: PORT });
    expect(data.connected).toBe(true);
    expect(data.browser).toBeDefined();
  });
});

// ─── Validation ─────────────────────────────────────

describe("Validation", () => {
  test("rejects invalid port", async () => {
    expect(((await get("/tabs?port=80")) as any).status).toBe(400);
    expect(((await get("/tabs?port=abc")) as any).status).toBe(400);
  });

  test("rejects missing params", async () => {
    expect(((await post("/click", { port: PORT })) as any).status).toBe(400);
  });

  test("neutralizes x/y string input", async () => {
    const data: any = await post("/scroll", { port: PORT, tabId: TAB_ID, x: "alert(1)" });
    expect(data.ok).toBe(true); // NaN → 0, safely ignored
  });
});

// ─── Perception ─────────────────────────────────────

describe("Perception", () => {
  test("screenshot", async () => {
    const data: any = await get(`/screenshot?port=${PORT}&id=${TAB_ID}`);
    expect(data.image?.length).toBeGreaterThan(100);
  });

  test("content + state", async () => {
    const data: any = await get(`/content?port=${PORT}&id=${TAB_ID}`);
    expect(data.content).toBeDefined();
    expect(data.state).toBeDefined();
  });

  test("snapshot", async () => {
    const data: any = await get(`/snapshot?port=${PORT}&id=${TAB_ID}`);
    expect(data.snapshot).toBeDefined();
    expect(typeof data.refCount).toBe("number");
  });

  test("snapshot + content", async () => {
    const data: any = await get(`/snapshot?port=${PORT}&id=${TAB_ID}&content=1`);
    expect(data.content).toBeDefined();
  });

  test("html", async () => {
    const data: any = await get(`/html?port=${PORT}&id=${TAB_ID}`);
    expect(data.html).toContain("<");
  });

  test("html with selector", async () => {
    const data: any = await get(`/html?port=${PORT}&id=${TAB_ID}&selector=body`);
    expect(data.html).toContain("<body");
  });

  test("pdf", async () => {
    const data: any = await get(`/pdf?port=${PORT}&id=${TAB_ID}`);
    expect(data.pdf?.length).toBeGreaterThan(100);
  }, 10000);

  test("form-state", async () => {
    const data: any = await get(`/form-state?port=${PORT}&id=${TAB_ID}`);
    expect(data.fields).toBeInstanceOf(Array);
  });

  test("perf", async () => {
    const data: any = await get(`/perf?port=${PORT}&id=${TAB_ID}`);
    // perf uses cdpSession — if it returns data, check domNodes; if error, that's ok too
    expect(data.domNodes !== undefined || data.error !== undefined).toBe(true);
  }, 10000);
});

// ─── Actions ────────────────────────────────────────

describe("Actions", () => {
  test("eval", async () => {
    const data: any = await post("/eval", { port: PORT, tabId: TAB_ID, expression: "1+1" });
    expect(data.value).toBe(2);
  });

  test("eval async", async () => {
    const data: any = await post("/eval", {
      port: PORT, tabId: TAB_ID,
      expression: "(async()=>await Promise.resolve(42))()",
    });
    expect(data.value).toBe(42);
  });

  test("scroll by y", async () => {
    const data: any = await post("/scroll", { port: PORT, tabId: TAB_ID, y: 50 });
    expect(data.ok).toBe(true);
  });

  test("viewport", async () => {
    const data: any = await post("/viewport", { port: PORT, tabId: TAB_ID, width: 1280, height: 720 });
    expect(data.ok).toBe(true);
  });

  test("keypress", async () => {
    const data: any = await post("/keypress", { port: PORT, tabId: TAB_ID, key: "tab" });
    expect(data).toHaveProperty("ok");
  }, 10000);

  test("click by coordinates", async () => {
    const data: any = await post("/click", { port: PORT, tabId: TAB_ID, x: 200, y: 200 });
    expect(data).toHaveProperty("ok");
  }, 10000);

  test("mouse-move", async () => {
    const data: any = await post("/mouse-move", {
      port: PORT, tabId: TAB_ID,
      path: [[10, 10], [50, 50]], duration: 30,
    });
    expect(data).toHaveProperty("ok");
  }, 10000);

  test("click by ref (if elements exist)", async () => {
    const snap: any = await get(`/snapshot?port=${PORT}&id=${TAB_ID}`);
    if (snap.refCount > 0) {
      const data: any = await post("/click", { port: PORT, tabId: TAB_ID, ref: 1 });
      expect(data).toHaveProperty("ok");
    }
  }, 10000);
});

// ─── Wait ───────────────────────────────────────────

describe("Wait", () => {
  test("pure delay", async () => {
    expect(((await post("/wait", { port: PORT, tabId: TAB_ID, timeout: 50 })) as any).ok).toBe(true);
  });

  test("selector", async () => {
    expect(((await post("/wait", { port: PORT, tabId: TAB_ID, selector: "body", timeout: 2000 })) as any).ok).toBe(true);
  });

  test("condition url-contains", async () => {
    expect(((await post("/wait", { port: PORT, tabId: TAB_ID, condition: "url-contains:google", timeout: 2000 })) as any).ok).toBe(true);
  });

  test("condition element-gone", async () => {
    expect(((await post("/wait", { port: PORT, tabId: TAB_ID, condition: "element-gone:.no-such-el", timeout: 1000 })) as any).ok).toBe(true);
  });
});

// ─── DevTools ───────────────────────────────────────

describe("Network Monitor", () => {
  test("enable → requests → clear → disable", async () => {
    expect(((await post("/network/enable", { port: PORT, tabId: TAB_ID })) as any).ok).toBe(true);
    expect(((await get(`/network/requests?port=${PORT}&id=${TAB_ID}`)) as any).requests).toBeDefined();
    expect(((await post("/network/clear", { port: PORT, tabId: TAB_ID })) as any).ok).toBe(true);
    await post("/network/disable", { port: PORT, tabId: TAB_ID });
  });
});

describe("Console Monitor", () => {
  test("enable → logs → clear → disable", async () => {
    expect(((await post("/console/enable", { port: PORT, tabId: TAB_ID })) as any).ok).toBe(true);
    expect(((await get(`/console/logs?port=${PORT}&id=${TAB_ID}`)) as any).logs).toBeDefined();
    expect(((await post("/console/clear", { port: PORT, tabId: TAB_ID })) as any).ok).toBe(true);
    await post("/console/disable", { port: PORT, tabId: TAB_ID });
  });
});

// ─── Storage ────────────────────────────────────────

describe("Storage & Cookies", () => {
  test("cookies", async () => {
    expect(((await get(`/cookies?port=${PORT}&id=${TAB_ID}`)) as any).cookies).toBeDefined();
  });

  test("storage set → get → remove", async () => {
    expect(((await post("/storage/set", { port: PORT, tabId: TAB_ID, key: "_t", value: "v" })) as any).ok).toBe(true);
    expect(((await get(`/storage?port=${PORT}&id=${TAB_ID}&type=local&key=_t`)) as any).data).toBe("v");
    expect(((await post("/storage/remove", { port: PORT, tabId: TAB_ID, key: "_t" })) as any).ok).toBe(true);
  });

  test("session export", async () => {
    const data: any = await get(`/session/export?port=${PORT}&id=${TAB_ID}`);
    expect(data.cookies).toBeDefined();
  });
});

// ─── Tabs ───────────────────────────────────────────

describe("Tabs", () => {
  test("list", async () => {
    expect(((await get(`/tabs?port=${PORT}`)) as any).tabs.length).toBeGreaterThan(0);
  });

  test("tab-name + tab-by-name", async () => {
    expect(((await post("/tab-name", { port: PORT, tabId: TAB_ID, name: "_t" })) as any).ok).toBe(true);
    expect(((await get(`/tab-by-name?port=${PORT}&name=_t`)) as any).tabId).toBe(TAB_ID);
  });
});

// ─── Per-Tab Proxy ──────────────────────────────────

describe("Per-Tab Proxy", () => {
  let proxyTabId = "";

  test("open with fake proxy", async () => {
    const data: any = await post("/open", { port: PORT, url: "https://httpbin.org/ip", proxy: "http://127.0.0.1:19999" });
    expect(data.tab || data.error).toBeDefined();
    proxyTabId = data.tab?.id || "";
    if (proxyTabId) CREATED_TABS.push(proxyTabId);
  });

  test("tabs shows proxy field", async () => {
    if (!proxyTabId) return;
    const tab = ((await get(`/tabs?port=${PORT}`)) as any).tabs.find((t: any) => t.id === proxyTabId);
    expect(tab?.proxy).toContain("19999");
  });

  test("proxy applied (error page)", async () => {
    if (!proxyTabId) return;
    await Bun.sleep(3000);
    const data: any = await post("/eval", { port: PORT, tabId: proxyTabId, expression: "location.href" });
    expect(data.value).toContain("chrome-error");
  }, 10000);
});

// ─── Extensions ─────────────────────────────────────

describe("Extensions", () => {
  test("list", async () => {
    expect(((await get(`/extensions?port=${PORT}`)) as any).extensions).toBeDefined();
  });
});

// ─── Profile ────────────────────────────────────────

describe("Profile", () => {
  test("save + list", async () => {
    expect(((await post("/profile/save", { port: PORT, name: "_t" })) as any).ok).toBe(true);
    expect(((await get("/profile/list")) as any).snapshots).toContain("_t");
    // Cleanup
    try { (await import("fs")).rmSync((await import("path")).join((await import("os")).homedir(), "cdpx/browser/snapshots/_t"), { recursive: true }); } catch {}
  });
});

// ─── Advanced ───────────────────────────────────────

describe("Advanced", () => {
  test("mock", async () => {
    const data: any = await post("/mock", { port: PORT, tabId: TAB_ID, patterns: [{ urlPattern: "_t_", responseBody: "ok" }] });
    expect(data).toHaveProperty("ok");
  }, 10000);

  test("batch", async () => {
    const data: any = await post("/batch", { port: PORT, tabId: TAB_ID, steps: [{ action: "eval", params: { expression: "1+1" } }] });
    expect(data.results?.[0]?.result?.value).toBe(2);
  });
});

// ─── Docs ───────────────────────────────────────────

describe("Docs", () => {
  test("GET /api/browser/docs", async () => {
    expect(await (await fetch(`http://127.0.0.1:${SERVER_PORT}/api/browser/docs`)).text()).toContain("CDPX Browser API"); // docs are public, no token needed
  });
});
